import fs from "node:fs/promises";
import path from "node:path";

// Generated by `npm run build:llms` in the root package (scripts/build-llms.js).
const LLMS_DIR = path.resolve(process.cwd(), "../dist");

export async function llmsFile(file: string, type: string) {
  const content = await fs.readFile(path.join(LLMS_DIR, file), "utf8");
  return new Response(content, {
    headers: { "Content-Type": `${type}; charset=utf-8` },
  });
}

export async function llmsPages() {
  const files = await fs.readdir(path.join(LLMS_DIR, "llms"), {
    recursive: true,
  });
  return files.filter((file) => file.endsWith(".md"));
}
